name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
      continue-on-error: true

    - name: Build project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./build

    - name: Check server status
      run: |
        for i in {1..6}; do
          echo "Checking server status: Attempt $i"
          response=$(curl -s -w "%{http_code}" -o response.txt http://localhost:3000/status)
          status=$(cat response.txt | jq -r '.status')
          echo "HTTP Status Code: $response"
          echo "Response Body: $(cat response.txt)"
          if [ "$status" != "OK" ]; then
            echo "Server status not OK. Attempt $i failed."
            sleep 10
          else
            echo "Server status OK. Proceeding."
            break
          fi
          if [ $i -eq 6 ]; then
            echo "Max attempts reached. Shutting down server."
            exit 1
          fi
        done
